server:
  error:
    whitelabel:
      enabled: false

spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:mysql://localhost:3307/picpin?characterEncoding=UTF-8&serverTimezone=UTC
    username: picpin_user
    password: picpin_user
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      format_sql: true
      hibernate:
        show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

oauth2:
  access_token_url: "https://kauth.kakao.com/oauth/token"
  get_user_info_url: "https://kapi.kakao.com/v2/user/me"
  redirect_url: ${KAKAO_REDIRECT_URL:http://localhost:8080/oauth2/code/kakao}
  client_id: ${KAKAO_CLIENT_ID:7ac056ec12a1aba0fc28bdbf20fbc0ce}
  client_secret: ${KAKAO_CLIENT_SECRET:j1nmy1aSMonYJE0FzII21cc4twPxobG1} # ${KAKAO_CLIENT_SECRET:#{null}}

jwt:
  issuer: ${JWT_ISSUER:local}
  secret: ${JWT_SECRET:AAAAAAAA}
  access_token_expire_time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME:3600}

aws:
  region: ap-northeast-2
  cloud_front: ${CLOUD_FRONT_DOMAIN:A}
  bucket: ${IMAGE_FARM_BUCKET_NAME:A}
  access_key: ${AWS_ACCESS_KEY:A}
  secret_key: ${AWS_SECRET_KEY:A}

---

server:
  error:
    whitelabel:
      enabled: false

spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://${PICPIN_DB_HOST}:${PICPIN_DB_PORT}/picpin?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${PICPIN_DB_USER}
    password: ${PICPIN_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      format_sql: false
      hibernate:
        show_sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

oauth2:
  access_token_url: "https://kauth.kakao.com/oauth/token"
  get_user_info_url: "https://kapi.kakao.com/v2/user/me"
  redirect_url: ${KAKAO_REDIRECT_URL}
  client_id: ${KAKAO_CLIENT_ID}
  client_secret: ${KAKAO_CLIENT_SECRET:#{null}}

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  access_token_expire_time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}

aws:
  region: ap-northeast-2
  cloud_front: ${CLOUD_FRONT_DOMAIN:A}
  bucket: ${IMAGE_FARM_BUCKET_NAME:A}
  access_key: ${AWS_ACCESS_KEY:A}
  secret_key: ${AWS_SECRET_KEY:A}
