GET {{apiAddress}}/albums
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbCIsInR5cGUiOiJLQUtBTyIsImV4cCI6MTY5OTU1MDU4NSwianRpIjoiMSJ9.VWlB4eHRa6i2y7_wksh2XPzfevQBC9XflXOQmNUqDjg
