PUT {{apiAddress}}/posts/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbCIsInR5cGUiOiJLQUtBTyIsImV4cCI6MTY5OTU0MjQ1OCwianRpIjoiMSJ9.hjvyYRbMoP5_tIBzIGET3GmbYj_YiW2Rp_JUm5NOF68

{
  "title": "bbb",
  "memo": "sample post memo",
  "marker_color_id": 1,
  "x": "126.97725",
  "y": "37.570892",
  "province_code": 11,
  "taken_photo_address": "서울..",
  "taken_photo_date": "2023-11-03",
  "photos": [
    {
      "id": 1,
      "image_url": "../image_url_1.jpg"
    }
  ]
}
