POST {{apiAddress}}/posts
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbCIsInR5cGUiOiJLQUtBTyIsImV4cCI6MTY5OTg3MDgxOCwianRpIjoiMSJ9.aJEc_ybOJP-hPG2uSHXNFqAHyA9JiQQ0R8u_P5CaROA

{
	"title": "aaa",
	"memo": "sample post memo",
	"marker_color_id": 1,
	"x": "126.97725",
	"y": "37.570892",
	"province_code": 11,
	"taken_photo_address": "서울..",
	"taken_photo_date": "2023-11-05",
	"photos": [
		"../image_url_1.jpg",
		"../image_url_2.jpg"
	]
}
