name: pull_resquest_ktlint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: '17'
        - name: Lint
          run: ./gradlew ktlintCheck
