name: pull_resquest_build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run infra
          uses: ./gradlew composeUp
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: '17'
        - name: Check running containers
          run: docker ps -a
        - name: Lint
          run: ./gradlew kilintCheck
        - name: Build
          run: ./gradlew build -x test
