POST {{apiAddress}}/albums
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbCIsInR5cGUiOiJLQUtBTyIsImV4cCI6MTY5OTg3MDgxOCwianRpIjoiMSJ9.aJEc_ybOJP-hPG2uSHXNFqAHyA9JiQQ0R8u_P5CaROA

{
  "title": "tempalbum2",
  "cover_image_url": "./cover_image_url.jpg",
  "photo_ids": [
    1
  ]
}
